### ISSUE TITLE
Attempt to invoke virtual method 'boolean android.os.Handler.post(java.lang.Runnable)' on a null object reference

### ISSUE THREAD

**Issue by riderx** [RevenueCat/purchases-hybrid-common#176]
**Describe the bug**
I tried to updated https://github.com/riderx/capacitor-purchases to latest version and the test app cannot run now

1. Environment
    1. Platform: Android 
    2. SDK version: 
    ```
    implementation "com.revenuecat.purchases:purchases:5.2.1"
    implementation "com.revenuecat.purchases:purchases-hybrid-common:3.2.4"
    ```
    3. OS version: 30
    4. XCode/Android Studio version: latest
    5. How widespread is the issue. Percentage of devices affected: 100%
2. [Debug logs](https://docs.revenuecat.com/docs/debugging) that reproduce the issue
```
2022-07-17 11:25:40.517 28790-28883/com.neufmoispourtoi.app E/AndroidRuntime: FATAL EXCEPTION: CapacitorPlugins
    Process: com.neufmoispourtoi.app, PID: 28790
    java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
        at com.getcapacitor.Bridge.lambda$callPluginMethod$0$com-getcapacitor-Bridge(Bridge.java:607)
        at com.getcapacitor.Bridge$$ExternalSyntheticLambda5.run(Unknown Source:8)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:223)
        at android.os.HandlerThread.run(HandlerThread.java:67)
     Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Method.invoke(Native Method)
        at com.getcapacitor.PluginHandle.invoke(PluginHandle.java:121)
        at com.getcapacitor.Bridge.lambda$callPluginMethod$0$com-getcapacitor-Bridge(Bridge.java:598)
        at com.getcapacitor.Bridge$$ExternalSyntheticLambda5.run(Unknown Source:8) 
        at android.os.Handler.handleCallback(Handler.java:938) 
        at android.os.Handler.dispatchMessage(Handler.java:99) 
        at android.os.Looper.loop(Looper.java:223) 
        at android.os.HandlerThread.run(HandlerThread.java:67) 
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.os.Handler.post(java.lang.Runnable)' on a null object reference
        at com.revenuecat.purchases.Purchases.dispatch(Purchases.kt:1258)
        at com.revenuecat.purchases.Purchases.<init>(Purchases.kt:159)
        at com.revenuecat.purchases.PurchasesFactory.createPurchases(PurchasesFactory.kt:77)
        at com.revenuecat.purchases.Purchases$Companion.configure(Purchases.kt:2037)
        at com.revenuecat.purchases.hybridcommon.CommonKt.configure(common.kt:306)
        at com.revenuecat.purchases.hybridcommon.CommonKt.configure$default(common.kt:287)
        at com.revenuecat.purchases.hybridcommon.CommonKt.configure(Unknown Source:25)
        at ee.forgr.plugin.capacitor_purchases.CapacitorPurchasesPlugin.setup(CapacitorPurchasesPlugin.java:43)
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.getcapacitor.PluginHandle.invoke(PluginHandle.java:121) 
        at com.getcapacitor.Bridge.lambda$callPluginMethod$0$com-getcapacitor-Bridge(Bridge.java:598) 
        at com.getcapacitor.Bridge$$ExternalSyntheticLambda5.run(Unknown Source:8) 
        at android.os.Handler.handleCallback(Handler.java:938) 
        at android.os.Handler.dispatchMessage(Handler.java:99) 
        at android.os.Looper.loop(Looper.java:223) 
        at android.os.HandlerThread.run(HandlerThread.java:67) 
```
the code to reproduce is there : https://github.com/riderx/capacitor-purchases/tree/android-v5
start a new capacitor app and add the plugin
4. The same init function was working in v4 purchase with v2 hybrid as you can see in main
you can see it by the PR https://github.com/riderx/capacitor-purchases/pull/8/files

**Comment by vegaro** [comment]
Thanks for reporting @riderx 

I think it's due to this change https://github.com/RevenueCat/purchases-android/commit/2bed17a041994cedf7e370d0f186c1d7b0fce078#diff-e019410c58657f001e6ba8be4f066c84c928f4e017ae3b3b6366cebfd64b9716R1251. 

It's weird because I have been testing the Android sample with no issues. I guess we have to revert the change

**Comment by riderx** [comment]
@vegaro it works, thanks !
